#!/bin/bash
[[ $# == 1 ]] || { echo "usage: $0 <DOCKER-TAG>"; exit 1; }
CGO_ENABLED=0 go build -v -o bin/hetzanetes
sudo docker build -t "duncanpierce/hetzanetes:$1" .
sudo docker push "duncanpierce/hetzanetes:$1"
