# sudo docker build -t duncanpierce/hetzanetes .
# sudo docker push duncanpierce/hetzanetes
apiVersion: v1
kind: Pod
metadata:
  name: spike
  namespace: hetzanetes-test
spec:
  serviceAccountName: hetzanetes-service
  containers:
    - name: hetzanetes
      image: duncanpierce/hetzanetes:latest
