apiVersion: batch/v1
kind: Job
metadata:
  name: add-worker-1
  namespace: kube-system
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: add-worker
          image: duncanpierce/hetzanetes
          command: ["/hetzanetes", "internal", "grow", "--server-type=cx11", "--node-suffix=1"]
          envFrom:
            - secretRef:
                name: k3s
            - secretRef:
                name: hcloud
