apiVersion: hetzanetes.duncanpierce.org/v1
kind: Cluster
metadata:
  name: "{{.ClusterName}}"
spec:
  channel: "{{.K3sReleaseChannel}}"
  nodeSets:
    - name: api
      apiServer: true
      nodeType: cpx11
      replicas: 1
      locations:
        - hel1
    - name: worker
      nodeType: cpx11
      replicas: 0
      locations:
        - hel1
