apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.hetzanetes.duncanpierce.org
spec:
  group: hetzanetes.duncanpierce.org
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                versions:
                  type: object
                  properties:
                    baseImage:
                      type: string
                    kubernetes:
                      type: string
                    hetzanetes:
                      type: string
                nodeSets:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - name
                  items:
                    type: object
                    required:
                      - name
                      - serverType
                      - replicas
                      - locations
                    properties:
                      name:
                        type: string
                      apiServer:
                        type: boolean
                      serverType:
                        type: string
                      replicas:
                        type: integer
                        minimum: 0
                      locations:
                        type: array
                        items:
                          type: string
            status:
              type: object
              properties:
                versions:
                  type: object
                  properties:
                    target:
                      type: string
                    nodes:
                      type: object
                      properties:
                        min:
                          type: string
                        max:
                          type: string
                    api:
                      type: object
                      properties:
                        min:
                          type: string
                        max:
                          type: string
                    workers:
                      type: object
                      properties:
                        min:
                          type: string
                        max:
                          type: string
                    channels:
                      type: array
                      x-kubernetes-list-type: map
                      x-kubernetes-list-map-keys:
                        - name
                      items:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          latest:
                            type: string
                clusterNetwork:
                  type: object
                  properties:
                    cloudId:
                      type: string
                    ipRange:
                      type: string
                nodeSets:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - name
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      generation:
                        type: integer
                      nodes:
                        type: array
                        x-kubernetes-list-type: map
                        x-kubernetes-list-map-keys:
                          - name
                        items:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            serverType:
                              type: string
                            location:
                              type: string
                            created:
                              type: string
                            cloudId:
                              type: string
                            clusterIP:
                              type: string
                            baseImage:
                              type: string
                            apiServer:
                              type: boolean
                            version:
                              type: string
                            joinEndpoint:
                              type: string
                            phase:
                              type: string
                            phaseChanged:
                              type: string
      subresources:
        status: {}
