apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.hetzanetes.duncanpierce.org
spec:
  group: hetzanetes.duncanpierce.org
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                versions:
                  type: object
                  properties:
                    baseImage:
                      type: string
                    kubernetes:
                      type: string
                    hetzanetes:
                      type: string
                nodeSets:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - name
                  items:
                    type: object
                    required:
                      - name
                      - nodeType
                      - replicas
                      - locations
                    properties:
                      name:
                        type: string
                      apiServer:
                        type: boolean
                      nodeType:
                        type: string
                      replicas:
                        type: integer
                        minimum: 0
                      locations:
                        type: array
                        items:
                          type: string
                      labels:
                        type: object
            status:
              type: object
              properties:
                nodeSets:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys:
                    - name
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      generation:
                        type: integer
      subresources:
        status: {}
