apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - cluster-crd.yaml
  - repair-cluster.yaml
  - https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml
  - https://raw.githubusercontent.com/hetznercloud/csi-driver/main/deploy/kustomization.yaml
patches:
  - patch.yaml