apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-cloud-controller-manager
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: hcloud-cloud-controller-manager
          command:
            - "/bin/hcloud-cloud-controller-manager"
            - "--cloud-provider=hcloud"
            - "--leader-elect=false"
            - "--allow-untagged-cloud"
            - "--allocate-node-cidrs=true"
            - "--cluster-cidr=10.42.0.0/16"
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HCLOUD_TOKEN
                  name: hcloud
            - name: HCLOUD_NETWORK
              valueFrom:
                secretKeyRef:
                  key: HCLOUD_NETWORK
                  name: hcloud
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: hcloud-csi
  name: hcloud-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: hcloud-csi-driver
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HCLOUD_TOKEN
                  name: hcloud
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcloud-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: hcloud-csi-driver
          env:
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HCLOUD_TOKEN
                  name: hcloud
