#cloud-config

package_update: true
package_upgrade: true
packages:
  - "curl"
  - "jq"
package_reboot_if_required: true
bootcmd:
  - "mkdir {{.InstallDirectory}}"
write_files:
  - path: "{{.InstallDirectory}}/kustomization.yaml"
    content: |
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      resources:
        - hetzner-ccm.yaml
        - hetzner-csi.yaml
      patches:
        - patch.yaml
  - path: "{{.InstallDirectory}}/patch.yaml"
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hcloud-cloud-controller-manager
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: hcloud-cloud-controller-manager
                command:
                  - "/bin/hcloud-cloud-controller-manager"
                  - "--cloud-provider=hcloud"
                  - "--leader-elect=false"
                  - "--allow-untagged-cloud"
                  - "--allocate-node-cidrs=true"
                  - "--cluster-cidr={{.PodIpRange}}"
runcmd:
  - curl -sfL 'https://get.k3s.io' | sh -s - server --cluster-init --disable servicelb --disable local-storage --disable-cloud-controller --kubelet-arg cloud-provider=external --flannel-iface={{template "get-private-interface.sh" .}}
  - kubectl create secret generic hetzanetes -n kube-system --from-literal=HCLOUD_TOKEN={{.HetznerApiToken}} --from-literal=HCLOUD_NETWORK={{.PrivateNetworkName}} --from-file=K3S_TOKEN=/var/lib/rancher/k3s/server/token --from-literal=K3S_URL="https://{{template "get-private-ip-address.sh" .}}:6443"
  - kubectl create secret generic hcloud -n kube-system --from-literal=token={{.HetznerApiToken}} --from-literal=network={{.PrivateNetworkName}}
  - kubectl create secret generic hcloud-csi -n kube-system --from-literal=token={{.HetznerApiToken}}
  - curl -sfL 'https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml' > {{.InstallDirectory}}/hetzner-ccm.yaml
  - curl -sfL 'https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.6.0/deploy/kubernetes/hcloud-csi.yml' > {{.InstallDirectory}}/hetzner-csi.yaml
  - kubectl apply -k {{.InstallDirectory}}
