#cloud-config

package_update: true
package_upgrade: true
packages:
  - "curl"
  - "jq"
package_reboot_if_required: true
bootcmd:
  - "mkdir {{.InstallDirectory}}"
write_files:
  - path: "{{.InstallDirectory}}/kustomization.yaml"
    content: |
      apiVersion: kustomize.config.k8s.io/v1beta1
      kind: Kustomization
      resources:
        - hetzner-secret.yaml
        - hetzner-csi-secret.yaml
        - hetzner-ccm.yaml
        - hetzner-csi.yaml
      patches:
        - patch.yaml
  - path: "{{.InstallDirectory}}/hetzner-secret.yaml"
    content: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: hcloud
        namespace: kube-system
      stringData:
        token: "{{.HetznerApiToken}}"
        network: "{{.PrivateNetworkName}}"
  - path: "{{.InstallDirectory}}/hetzner-csi-secret.yaml"
    content: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: hcloud-csi
        namespace: kube-system
      stringData:
        token: "{{.HetznerApiToken}}"
  - path: "{{.InstallDirectory}}/patch.yaml"
    content: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hcloud-cloud-controller-manager
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: hcloud-cloud-controller-manager
                command:
                  - "/bin/hcloud-cloud-controller-manager"
                  - "--cloud-provider=hcloud"
                  - "--leader-elect=false"
                  - "--allow-untagged-cloud"
                  - "--allocate-node-cidrs=true"
                  - "--cluster-cidr={{.PodIpRange}}"
runcmd:
  {{/* TODO there is also --flannel-conf : where is it and what's in it? */}}
  - "curl -sfL 'https://get.k3s.io' | sh -s - --disable servicelb --disable local-storage --disable-cloud-controller --kubelet-arg cloud-provider=external --flannel-iface={{template "get-private-interface.sh" .}}"
  - "curl -sfL 'https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml' > {{.InstallDirectory}}/hetzner-ccm.yaml"
  - "curl -sfL 'https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.6.0/deploy/kubernetes/hcloud-csi.yml' > {{.InstallDirectory}}/hetzner-csi.yaml"
  - "kubectl apply -k {{.InstallDirectory}}"
