apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: kube-system
  annotations:
    load-balancer.hetzner.cloud/location: hel1
    load-balancer.hetzner.cloud/use-private-ip: "true"
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer
