apiVersion: hetzanetes.duncanpierce.org/v1
kind: Cluster
metadata:
  name: "{{.ClusterName}}"
spec:
  channel: stable
  nodeSets:
    - name: api
      apiServer: true
      nodeType: cpx11
      replicas: 1
      locations:
        - hel1
