apiVersion: hetzanetes.duncanpierce.org/v1
kind: Cluster
metadata:
  name: "{{.ClusterName}}"
spec:
  nodeSets:
    - name: api
      apiServer: true
      serverType: cx11
      replicas: 1
      locations:
        - hel1
